on:
  workflow_call:
    inputs:
      IMAGE:
        type: string
        default: "ghcr.io/missmp/${{ github.event.repository.name }}"

jobs:
  Build:
    runs-on: ubuntu-latest-l
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ko-build/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: ${{ inputs.IMAGE }}
      - run: ko build -t $(git describe --tags)
