name: Build Template

on:
  workflow_call:
    inputs:
      IMAGE:
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest-l
    needs: Test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ko-build/setup-ko@v0.6
      - run: ko build -t $(git describe --tags)
