on:
  workflow_call:
    inputs:
      IMAGE:
        type: string
        default: "ghcr.io/missmp/${{ github.event.repository.name }}"
      BUILD_PATH:
        type: string
        default: "*.go"
    secrets:
      GH_TOKEN:
        required: true
jobs:
  Build:
    runs-on: ubuntu-latest-l
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      USERNAME: ${{ github.actor }}
      KO_DOCKER_REPO: ${{ inputs.IMAGE }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ko-build/setup-ko@v0.6
      - run: |
          echo "${GH_TOKEN}" | ko login ghcr.io --username ${USERNAME} --password-stdin
          ko build --bare -t $(git describe --tags) ${{ inputs.BUILD_PATH }}
